# Generated by Django 5.2.1 on 2025-05-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personas',
            new_name='Persona',
        ),
    ]
