# Generated by Django 5.2.1 on 2025-05-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_rename_personas_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
