# Generated by Django 5.2.1 on 2025-05-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaNotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
    ]
