# Generated by Django 5.2.1 on 2025-05-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaNotas', '0002_rename_alumno_alumnos_rename_curso_cursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
