# Generated by Django 5.2.1 on 2025-05-24 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaNotas', '0003_rename_alumnos_alumno_rename_cursos_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='CUI',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='NotasAlumnosPorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaNotas.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaNotas.curso')),
            ],
        ),
    ]
