# Generated by Django 5.2.4 on 2025-07-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
