# Generated by Django 5.2.2 on 2025-06-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.ManyToManyField(to='Relaciones.movie')),
            ],
        ),
    ]
